version: "3.3"
services:
    server:
        build: ./server
        ports: 
            - 5052:5000
        command: npm run dev
        volumes: 
            - ./server/src/:/app/src/
    mongodb:
        image: mongo
    client:
        container_name: client-service
        build:
            context: ./client/my-app
        volumes:
            - '/my-app/node_modules'
        ports:
            - 8080:3000
        environment:
            - CHOKIDAR_USEPOLLING=true